### ISSUE TITLE
`reduceFunc` returning first character of UUID string in some cases

### ISSUE THREAD

**Issue by ribose-jeffreylau** [glossarist/paneron-extension-glossarist#7]
https://github.com/glossarist/paneron-extension-glossarist/blob/a0c299e858bafaba88c9b00addbb05375312b7d5/src/classes/localizedConcept/util.ts#L30

The above code would pluck the first character of a UUID string and return it, in certain situations where `value` is a `string` and not an array.

See: https://github.com/geolexica/isotc211-glossary/issues/46

**Comment by strogonoff** [comment]
@ribose-jeffreylau Thanks for noting. Let’s try to understand what happens here.

The outcome of the map stage should always be an array—see `mapReduce()` [in Paneron](https://github.com/paneron/paneron/blob/3678dad8a744a51e9f936139a467319c7f849f27/src/datasets/main/loadedDatasets.ts#L344-L357).

On that resulting array, we call `reduce()` (as per above link). According to [MDN reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce#callbackfn), if we call `array.reduce(func)`, our func will get called as `func(accumulator, value)`, where `value` is equal to `array[0]` (and on each subsequent call it is the next item in the array, 1, 2, etc.), whereas `accumulator` would be the result of the previous call.

Which means my original implementation was probably incorrect, since if our array is an array of UUIDs then `value` would *always* be an UUID, and `value[0]` should *always* return the first character from given UUID and would *never* return the actual UUID. Can you confirm that’s the case?

(In Glossarist, any given localized concept is expected to only be referenced by one universal concept, so the array will always have a single element. That’s why we don’t really need any fancy logic in this reduce function.)

Based on this, I *suspect* we may as well just return `value` and avoid the extra condition as in your PR.

**Comment by strogonoff** [comment]
@ribose-jeffreylau the problem was due to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce#edge_cases. See edge case example with “callback is not invoked”.

This means that returning the value will fix the issue for now, and I’ll merge the PR, but in the long run to avoid this we should provide `initialValue` where we do the mapping to ensure the function is invoked if mapping stage returned only one element.

**Comment by strogonoff** [comment]
This was released in extension version 2.0.18.
